### ISSUE TITLE
Ability for change-makers to set up a Price tolerance 

### ISSUE THREAD

**Issue by vgaudis** [StableTechnologies/TEZEX#82]
Change-makers should be able to set their price tolerance to match user swap demand.
Prices are still Oracle informed but liquidity is only in play respective to each change-maker based on their price tolerance level that they indicate.

Example: ETHtz/ETH
    * current oracle price: 3000$
    * LP tolerance: 1.5%:1.5%

**Comment by KevinMehrabi** [comment]
The example is not relevant because ETHtz/ETH are 2 like-assets. The current method is good for those.

The issue here is for non like-assets. Price tolerance should just refer to particular threshold of price.

Example: ETHtz/USDtz
Oracle price of ETH **=** $3000(USD)

Say a Changemakers is not willing to part with their ETHtz for USDtz unless the price of ETH(ETHtz) goes up to **at least** $3500. Price tolerance set by a Changemakers would indicate swap terms are permissible **if and only if** Oracle reading reports ETH **≥** $3500(USD)

**Comment by vgaudis** [comment]
Replaced by #109
